import { ColorGradingTexture, DefaultRenderingPipeline, Scene } from "@babylonjs/core";
import { asset } from "./assets";

/**
 * The warm "Black Flag / sun-soaked Caribbean" color grade.
 *
 * Babylon v9's ColorGradingTexture only parses `.3dl` LUTs, and that file is
 * plain text we can author procedurally (no binary asset, no external tool).
 * `public/lut/tropical_caribbean.3dl` is a 32^3 split-tone LUT:
 *   - deep CYAN shadows (red pulled down, blue pushed up), and
 *   - WARM YELLOW highlights (red/green pushed up, blue cut),
 *   with near-neutral midtones and a light saturation lift so the grade reads
 *   cinematic without washing out or lifting the blacks.
 *
 * It is generated by a throwaway Node script (see the task notes); regenerate
 * by recomputing the same split-tone formula into a `.3dl` with r-slowest /
 * g-middle / b-fastest line order. The entry order matters — it matches
 * Babylon's `_load3dlTexture` reader.
 */
export const TROPICAL_LUT_URL = asset("/lut/tropical_caribbean.3dl");

/**
 * How strongly to blend the LUT over the un-graded frame (0..1). Kept below 1
 * so a little of the ACES result survives: the grade warms the image without
 * fully overriding the existing tone map, which is what stops it washing out.
 */
const GRADE_BLEND = 0.9;

/**
 * Attach the tropical grade to a DefaultRenderingPipeline's image-processing
 * pass. Additive + revertible: pass `null` back in to remove the LUT.
 *
 * The grade is part of the image-processing stage, so it is automatically
 * gated by quality: when `pipeline.imageProcessingEnabled` is false (the "low"
 * preset in createGame) the shader drops the COLORGRADING define entirely, so
 * this costs nothing on weak GPUs without any extra wiring here.
 *
 * @param pipeline The already-built filmic pipeline to grade.
 * @param scene    The scene that owns the texture (needed by ColorGradingTexture).
 * @param url      LUT asset path; swap for a different look.
 * @param blend    0..1 strength of the grade over the raw image.
 */
export function applyColorGrade(
	pipeline: DefaultRenderingPipeline,
	scene: Scene,
	url: string = TROPICAL_LUT_URL,
	blend: number = GRADE_BLEND
): void {
	// Image processing must be on for the grading hook to exist at all.
	if (!pipeline.imageProcessingEnabled || !pipeline.imageProcessing) {
		return;
	}

	if (url === "") {
		// Revert: drop the LUT and disable the effect.
		pipeline.imageProcessing.colorGradingTexture = null;
		pipeline.imageProcessing.colorGradingEnabled = false;
		return;
	}

	// `level` is consumed as the mix weight (colorTransformSettings.w) in the
	// image-processing shader, so it scales the whole grade.
	const lut = new ColorGradingTexture(url, scene);
	lut.level = Math.min(1, Math.max(0, blend));

	pipeline.imageProcessing.colorGradingTexture = lut;
	pipeline.imageProcessing.colorGradingEnabled = true;
}
